IllnessPredictor/IllnessPredictor/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('', include('IllnessWeb.urls')),
    path('admin/', admin.site.urls),
]

IllnessPredictor/IllnessWeb/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'IllnessWeb'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search, name= 'search'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='IllnessWeb/login.html', authentication_form=LoginForm), name= 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='IllnessWeb/logout.html'), name= 'logout'),
]

IllnessPredictor/IllnessWeb/models.py
from django.db import models

# Create your models here.

IllnessPredictor/IllnessWeb/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

IllnessPredictor/IllnessWeb/views.py
from django.shortcuts import render, redirect
from .forms import LoginForm
from django.contrib.auth.decorators import login_required

from .forms import SignupForm
from item.models import Item, SymptomMatcher, PhraseExtractor

def index(request): 
    return render(request, 'IllnessWeb/index.html')

def search(request):
    symptom_matcher = SymptomMatcher()
    symptom_matcher.load_symptoms()
    query = request.GET.get('query', '')
    items = Item.objects.all()

    if query:
        phrase_extractor = PhraseExtractor(query)
        phrase_extractor.process()
        phrases = phrase_extractor.get_phrases()

        matched_symptoms = symptom_matcher.check_symptom_with_word(phrases)

        combined_descriptions = []
        for symptom in matched_symptoms:
            descriptions = symptom_matcher.get_symptom_description(symptom)
            combined_descriptions.extend(descriptions)

        combined_descriptions = list(set(combined_descriptions))

        matched_symptoms_combined = list(set(matched_symptoms))

        filtered_items = items.filter(name__in=combined_descriptions)

        illness_percentages = {}
        for description in combined_descriptions:
            collection_names = symptom_matcher.db.list_collection_names()

            for collection_name in collection_names:
                current_collection = symptom_matcher.db[collection_name]
                documents = current_collection.find({"description": description}, {"symptoms": 1})

                for document in documents:
                    document_symptoms = document.get("symptoms", [])
                    matched_percentage = (len(set(matched_symptoms_combined) & set(document_symptoms)) / len(document_symptoms)) * 100
                    illness_percentages[description] = matched_percentage

        return render(request, 'IllnessWeb/search.html', {
            'items': filtered_items,
            'query': query, 
            'illness_percentages': illness_percentages,
        })
    else:
        return render(request, 'IllnessWeb/search.html', {
            'query': query, 
        })


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'IllnessWeb/signup.html', {
        'form': form
    })

IllnessPredictor/IllnessWeb/templates/IllnessWeb/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock %} | Illness Predictor</title>
</head>
<body class="flex flex-col min-h-screen">
    <div class="flex-grow" style="background-color: #9acaca;">
        <nav class="py-6 px-6 flex justify-between items-center " style="background-color: white;">
            <a href="/" class="text-xl font-semibold">Illness Predictor</a>

            <div class="space-x-6">
                {% if request.user.is_authenticated %}
                    <div class="flex justify-between gap-4 items-center">
                        <h1 class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl">User: {{ user.get_username }}</h1>
                        <a href="{% url 'IllnessWeb:index' %}" class="px-6 py-3 text-lg font-semibold bg-green-500 text-white rounded-xl hover:bg-green-700">Home</a>
                        <a href="{% url 'IllnessWeb:logout' %}" class="px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl hover:bg-red-700">Logout</a>
                    </div>
                {% else %}
                    <a href="{% url 'IllnessWeb:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                    <a href="{% url 'IllnessWeb:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
                {% endif %}
            </div>
        </nav>

        <div class="px-6 py-6 font-semibold text-center flex-grow" >
            {% block contend %}
            {% endblock %}
        </div>
    </div>

    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>
            <p class="text-lg text-gray-500">Our compnay has developed a software that combines the latest advancements in machine learning and medical expertise to provide reliable predictions, aiding in early detection and proactive healthcare management. Our user-friendly interface ensures a seamless experience, allowing users to input their symptoms easily and receive instant results.</p>
        </div>

        <div class="w-1/4">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
            <ul class="space-y-2">
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>
            </ul>
        </div>
    </footer>
</body>
</html>

IllnessPredictor/IllnessWeb/templates/IllnessWeb/index.html
{% extends 'IllnessWeb/base.html' %}

{% block title %}Welcome{% endblock %}

{% block contend %}
    <h1 class="text-7xl mt-10">Illness Predictor</h1>
    <div class="flex items-center justify-center">
        <p class="whitespace-normal w-1/3 mt-40 mb-20 text-xl">Whether you're a medical professional or an individual curious about your health, our product is here to help you. With our innovative solution, you can easily assess your health condition and gain valuable insights.</p>
    </div>
    {% if request.user.is_authenticated %}
        <div class="flex justify-center">
            <a href="{% url 'IllnessWeb:search' %}"  class="absolute mt-10 bg-teal-700 text-white hover:bg-teal-900 font-bold py-7 px-8 rounded-full text-3xl w-4/6" >Go to the Search Engine</a>
        </div>
    {% else %}
        <div class="flex justify-center">
            <a href="{% url 'IllnessWeb:login' %}"  class="absolute mt-10 bg-teal-700 text-white hover:bg-teal-900 font-bold py-7 px-8 rounded-full text-3xl w-4/6" >Go to the Search Engine</a>
        </div>
    {% endif %}
{% endblock %}

IllnessPredictor/IllnessWeb/templates/IllnessWeb/login.html
{% extends 'IllnessWeb/base.html' %}

{% block title %}Log in{% endblock %}

{% block contend %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2 ">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

IllnessPredictor/IllnessWeb/templates/IllnessWeb/search.html
{% extends 'IllnessWeb/base.html' %}

{% block title %}Search{% endblock %}

{% block contend %}
    <h1 class="text-7xl mt-10">Illness Predictor</h1>
    <div class="flex justify-center">
        <div class="relative w-1/2 mt-32">
            <form method="get" action="{% url 'IllnessWeb:search' %}">
                <input
                    name = 'query'
                    value="{{ query }}"
                    type="text"
                    placeholder="Search"
                    class="w-full py-4 px-4 rounded-full border border-gray-300 text-lg focus:outline-none "
                />
                <button
                    class="absolute right-0 top-0 bottom-0 py-3 px-4 bg-blue-500 text-white rounded-r-lg hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
                >
                    Search
                </button>
            </form>
        </div>
    </div>
    <div class="mt-6 px-6 py-12 bg-gray-500 h-50% rounded-xl overflow-auto">
        <h2 class="mb-12 text-2xl text-center text-6xl bg-gray-100 p-4 rounded-full">Illnesses</h2>

        <div class="grid grid-cols-3 gap-3 bg-gray-100 rounded-xl">
            {% for item in items %}
                    <div class="p-6">
                        <div class="p-6 bg-gray-300 rounded-t-xl">
                            <h2 class="text-3xl">{{ item.name }}</h2>
                        </div>
                        <div>
                            <img src="{{ item.img_url }}" >
                        </div>
                        <div class="p-6 bg-gray-300">
                            <h2 class="text-2xl bg-gray-500 rounded-full m-5 p-4">Description</h2>
                            <h2 class="text-xl">{{ item.description }}</h2>
                        </div>
                        <div class="p-6 bg-gray-300">
                            <h2 class="text-2xl bg-gray-500 rounded-full mb-5 p-4">Treatment</h2>
                            <h2 class="text-xl">{{ item.treatment }}</h2>
                        </div>
                        <div class="p-6 bg-gray-300 rounded-b-xl">
                            <h2 class="text-2xl bg-gray-500 rounded-full mb-5 p-4">Specialist</h2>
                            <h2 class="text-xl">{{ item.specialist }}</h2>
                        </div>
                    </div>  
            {% endfor %}
        </div>
    </div>
{% endblock %}

IllnessPredictor/IllnessWeb/templates/IllnessWeb/signup.html
{% extends 'IllnessWeb/base.html' %}

{% block title %}Sign up{% endblock %}

{% block contend %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2 ">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}